apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: cloudproject
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-mongo
      port: 27017
      protocol: TCP
      targetPort: tcp-mongo
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP