// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/rfid": {
            "put": {
                "description": "Update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "description": "input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateRfidInputParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/rfid/:epc": {
            "get": {
                "description": "Get One By EPC",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid"
                ],
                "summary": "Get One By EPC",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/rfid/generate": {
            "post": {
                "description": "Generate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid"
                ],
                "summary": "Generate",
                "parameters": [
                    {
                        "description": "input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.RfidGenerateInput"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/rfid/recycle": {
            "post": {
                "description": "Recycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid"
                ],
                "summary": "Recycle",
                "parameters": [
                    {
                        "description": "input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RecycleRfidInputParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/rfid/validate": {
            "post": {
                "description": "Validate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid"
                ],
                "summary": "Validate",
                "parameters": [
                    {
                        "description": "input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ValidateRfidInputParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check Health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Check Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ResponseDTO": {
            "type": "object",
            "properties": {
                "data": {},
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "enum.RfidRefType": {
            "type": "string",
            "enum": [
                "TO",
                "PO",
                "SHIP"
            ],
            "x-enum-varnames": [
                "RfidRefTypeTO",
                "RfidRefTypePO",
                "RfidRefTypeShip"
            ]
        },
        "enum.RfidStatus": {
            "type": "string",
            "enum": [
                "DRAFT",
                "EXFACTORY",
                "DCRECEIVED",
                "DCDISPATCHED",
                "STORERECEIVED",
                "DCCOUNTED",
                "DISMISSED"
            ],
            "x-enum-varnames": [
                "RfidStatusDraft",
                "RfidStatusExFactory",
                "RfidStatusDcReceived",
                "RfidStatusDcDispatched",
                "RfidStatusStoreReceived",
                "RfidStatusDcCounted",
                "RfidStatusDismissed"
            ]
        },
        "v1.RecycleRfidInputParams": {
            "type": "object",
            "properties": {
                "epc": {
                    "type": "string"
                }
            }
        },
        "v1.RfidGenerateInput": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "v1.SkuEpcDTO": {
            "type": "object",
            "properties": {
                "epc": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateRfidInputParams": {
            "type": "object",
            "properties": {
                "epc": {
                    "type": "string"
                },
                "refId": {
                    "type": "string"
                },
                "refType": {
                    "$ref": "#/definitions/enum.RfidRefType"
                },
                "status": {
                    "$ref": "#/definitions/enum.RfidStatus"
                }
            }
        },
        "v1.ValidateRfidInputParams": {
            "type": "object",
            "properties": {
                "epcList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.SkuEpcDTO"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	//LeftDelim:        "{{",
	//RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
